services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
      - /sys/class/thermal/thermal_zone0/temp:/thermal/thermal_zone0/temp
    devices:
      - /dev/ttyUSB0
    restart: unless-stopped
    privileged: true
    network_mode: host

networks:
  default:
    external: true
    name: nginx
