services:
  adguardhome:
    image: adguard/adguardhome
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 8090:80/tcp
      - 3000:3000/tcp
    volumes:
      - ./config:/opt/adguardhome/conf
      - ./work:/opt/adguardhome/work
